# 3次元マップデータ（3層: z=0, 1, 2）

map_data = [
    # z=0 (1段)
    [
        "--        TDHEFVTGADQRIFIGKJABGQICLQQDHFQ         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        GXQBFBCHGUJHSRMLHBBCNABAKCLRSLW         ",
        "--        DXQBFBCHGUJHSRMLHBBCNABAKCLRSLH         ",
        "--        HDBRLJPNJACQLIEMEKAQEATHKIHMBEB         ",
        "--                                                ",
        "--                                                ",
        "--        DCADGKCGFTONPSCSTBEKZRPAELQPOFD         ",
        "          CCADGKCGFTONPSCSTBEKZRPAELQPOFQ         ",
        "          RJFFQCSGFTSIDOCNBNFNENASMJOGBTO         ",
        "                                                  ",
        "                                                  ",
        "          TNBJNDFPPCMMEMGNSKTPBFFOSMJQBDF         ",
        "          CNBJNDFPPCMMEMGNSKTPBFFOSMJQBDP         ",
        "          APDHLJQABBBOGRHPAHQBPDCRIIMENPF         ",
        "                                                  ",
        "                                                  ",
        "    1     JSFGGHDAQDPHLMSFSEPIKPSGOSHDYLJ    $    ",
    ],
    # z=1 (2段)
    [
        "--        ABCDEFGHIJKLMNOPQRSTUVWXYZABCDE         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        FGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ         ",
        "--        KGHIJKLMNOPQRSTUVWXYZABCDEFGHIL         ",
        "--        MNOPQRSTUVWXYZABCDEFGHIJKLMNOPS         ",
        "--                                                ",
        "--                                                ",
        "--        QRSTUVWXYZABCDEFGHIJKLMNOPQRSTU         ",
        "          VRSTUVWXYZABCDEFGHIJKLMNOPQRSTW         ",
        "          XYZABCDEFGHIJKLMNOPQRSTUVWXYZAF         ",
        "                                                  ",
        "                                                  ",
        "          BCDEFGHIJKLMNOPQRSTUVWXYZABCDEF         ",
        "          FCDEFGHIJKLMNOPQRSTUVWXYZABCDEG         ",
        "          HIJKLMNOPQRSTUVWXYZABCDEFGHIJKL         ",
        "                                                  ",
        "                                                  ",
        "    1     LMNOPQRSTUVWXYZABCDEFGHIJKLMNOP    $    ",
    ],
    # z=2 (3段)
    [
        "--        ZYXWVUTSRQPONMLKJIHGFEDCBAZYXWV         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        WVUTSRQPONMLKJIHGFEDCBAZYXWVUTS         ",
        "--        SVUTSRQPONMLKJIHGFEDCBAZYXWVUTR         ",
        "--        QPONMLKJIHGFEDCBAZYXWVUTSRQPONM         ",
        "--                                                ",
        "--                                                ",
        "--        ONMLKJIHGFEDCBAZYXWVUTSRQPONMLK         ",
        "          KNMLKJIHGFEDCBAZYXWVUTSRQPONMLJ         ",
        "          IHGFEDCBAZYXWVUTSRQPONMLKJIHGFG         ",
        "                                                  ",
        "                                                  ",
        "          EDCBAZYXWVUTSRQPONMLKJIHGFEDCBH         ",
        "          ADCBAZYXWVUTSRQPONMLKJIHGFEDCBZ         ",
        "          YXWVUTSRQPONMLKJIHGFEDCBAZYXWVU         ",
        "                                                  ",
        "                                                  ",
        "    1     UTSRQPONMLKJIHGFEDCBAZYXWVUTSRT    $    ",
    ],
]
