# 3次元マップデータ（3層: z=0, 1, 2）

map_data = [
    # z=0 (1段)
    [
        "--        TDHEFVTGADQRIFIGKJABGQICLQQDHFQ         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        GXQBFBCHGUJHSRMLHBBCNABAKCLRSLW         ",
        "--        D                             H         ",
        "--        HDBRLJPNJACQLIEMEKAQEATHKIHMBEB         ",
        "--                                                ",
        "--                                                ",
        "--        DCADGKCGFTONPSCSTBEKZRPAELQPOFD         ",
        "          C                             Q         ",
        "          RJFFQCSGFTSIDOCNBNFNENASMJOGBTO         ",
        "                                                  ",
        "                                                  ",
        "          TNBJNDFPPCMMEMGNSKTPBFFOSMJQBDF         ",
        "          C                             P         ",
        "          APDHLJQABBBOGRHPAHQBPDCRIIMENPF         ",
        "                                                  ",
        "                                                  ",
        "    1     JSFGGHDAQDPHLMSFSEPIKPSGOSHDYLJ    $    ",
    ],
    # z=1 (2段)
    [
        "--        ABCDEFGHIJKLMNOPQRSTUVWXYZABCDE         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        FGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ         ",
        "--        K                             L         ",
        "--        MNOPQRSTUVWXYZABCDEFGHIJKLMNOPS         ",
        "--                                                ",
        "--                                                ",
        "--        QRSTUVWXYZABCDEFGHIJKLMNOPQRSTU         ",
        "          V                             W         ",
        "          XYZABCDEFGHIJKLMNOPQRSTUVWXYZAF         ",
        "                                                  ",
        "                                                  ",
        "          BCDEFGHIJKLMNOPQRSTUVWXYZABCDEF         ",
        "          F                             G         ",
        "          HIJKLMNOPQRSTUVWXYZABCDEFGHIJKL         ",
        "                                                  ",
        "                                                  ",
        "    1     LMNOPQRSTUVWXYZABCDEFGHIJKLMNOP    $    ",
    ],
    # z=2 (3段)
    [
        "--        ZYXWVUTSRQPONMLKJIHGFEDCBAZYXWV         ",
        "--                                                ",
        "--                                                ",
        "--                                                ",
        "--        WVUTSRQPONMLKJIHGFEDCBAZYXWVUTS         ",
        "--        S                             R         ",
        "--        QPONMLKJIHGFEDCBAZYXWVUTSRQPONM         ",
        "--                                                ",
        "--                                                ",
        "--        ONMLKJIHGFEDCBAZYXWVUTSRQPONMLK         ",
        "          K                             J         ",
        "          IHGFEDCBAZYXWVUTSRQPONMLKJIHGFG         ",
        "                                                  ",
        "                                                  ",
        "          EDCBAZYXWVUTSRQPONMLKJIHGFEDCBH         ",
        "          A                             Z         ",
        "          YXWVUTSRQPONMLKJIHGFEDCBAZYXWVU         ",
        "                                                  ",
        "                                                  ",
        "    1     UTSRQPONMLKJIHGFEDCBAZYXWVUTSRT    $    ",
    ],
]
